FROM google/dart
WORKDIR /app
ADD pubspec.* /app/
RUN pub get
ADD . /app/
RUN chmod 755 /app/dart_run.sh && chown root:root /app/dart_run.sh
RUN pub get --offline
EXPOSE 8080 
CMD []
ENTRYPOINT ["/app/dart_run.sh"]
